/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makanan;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class forgetpass extends javax.swing.JFrame 
{

    String mail;
    String usernames;
    String Passwordreset;
    
    
    public forgetpass() {
        initComponents();
        coverforget.setBackground(new Color(0,51,51,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        coverforget = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reset = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailforget = new javax.swing.JTextField();
        Enterednewpass = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        usernameshow = new javax.swing.JTextField();
        Generateuser = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Backforget = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coverforget.setBackground(new java.awt.Color(0, 51, 51));
        coverforget.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Your Email");
        coverforget.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, -1));

        reset.setForeground(new java.awt.Color(153, 153, 153));
        reset.setText("Enter New Pass");
        reset.setBorder(null);
        reset.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resetFocusGained(evt);
            }
        });
        coverforget.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 210, 30));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/ha.png"))); // NOI18N
        coverforget.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 100, -1));

        emailforget.setForeground(new java.awt.Color(153, 153, 153));
        emailforget.setText("Enter Your Mail");
        emailforget.setBorder(null);
        emailforget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailforgetMouseClicked(evt);
            }
        });
        emailforget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailforgetActionPerformed(evt);
            }
        });
        coverforget.add(emailforget, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 370, 40));

        Enterednewpass.setBackground(new java.awt.Color(0, 60, 51));
        Enterednewpass.setForeground(new java.awt.Color(255, 255, 255));
        Enterednewpass.setText("Entered New Pass");
        Enterednewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterednewpassActionPerformed(evt);
            }
        });
        coverforget.add(Enterednewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 30));
        coverforget.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 20));

        usernameshow.setForeground(new java.awt.Color(153, 153, 153));
        usernameshow.setText("Enter Your Username");
        usernameshow.setBorder(null);
        usernameshow.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameshowFocusGained(evt);
            }
        });
        usernameshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameshowActionPerformed(evt);
            }
        });
        coverforget.add(usernameshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 30));

        Generateuser.setBackground(new java.awt.Color(0, 60, 51));
        Generateuser.setForeground(new java.awt.Color(255, 255, 255));
        Generateuser.setText("Generate Username");
        Generateuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateuserActionPerformed(evt);
            }
        });
        coverforget.add(Generateuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 150, 30));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("This is Unoffical Facultas Kopi Web");
        coverforget.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 220, 20));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Facebook : FAKULTAS KOPI JAKARTA");
        coverforget.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 260, 20));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Facebook : FAKULTAS KOPI JAKARTA");
        coverforget.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 190, 20));

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Instagram: FAKULTAS KOPI");
        coverforget.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 190, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Emergency Form");
        coverforget.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("New Password");
        coverforget.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Username");
        coverforget.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, -1));

        Backforget.setBackground(new java.awt.Color(0, 153, 102));
        Backforget.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        Backforget.setForeground(new java.awt.Color(255, 255, 255));
        Backforget.setText("BACK");
        Backforget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackforgetActionPerformed(evt);
            }
        });
        coverforget.add(Backforget, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 120, 30));

        jPanel3.add(coverforget, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 440, 550));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/background-close-up-color-1227648.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailforgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailforgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailforgetActionPerformed

    private void usernameshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameshowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameshowActionPerformed

    private void EnterednewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterednewpassActionPerformed
       Passwordreset = reset.getText();
      if(usernameshow.getText().equals(usernames))
      {
          Register C = new Register();
          C.method(usernames, Passwordreset);
          this.dispose();
          C.setVisible(true);
      }
      else
      {
         JOptionPane.showMessageDialog(null, "First Genrate USername");
      }
    }//GEN-LAST:event_EnterednewpassActionPerformed

    private void GenerateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateuserActionPerformed
         String takein  = emailforget.getText();
       
       if(takein.equals(mail))
       {
           usernameshow.setText(usernames);
           
       }
       else
       {
           JOptionPane.showMessageDialog(null, "Incorrect Email");
       }
    }//GEN-LAST:event_GenerateuserActionPerformed

    private void emailforgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailforgetMouseClicked
       emailforget.setText("");
    }//GEN-LAST:event_emailforgetMouseClicked

    private void usernameshowFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameshowFocusGained
      usernameshow.setText("");
    }//GEN-LAST:event_usernameshowFocusGained

    private void resetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetFocusGained
         reset.setText("");
    }//GEN-LAST:event_resetFocusGained

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x, y);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void BackforgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackforgetActionPerformed
        Register S = new Register();
        this.dispose();
        S.setVisible(true);
    }//GEN-LAST:event_BackforgetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgetpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backforget;
    private javax.swing.JButton Enterednewpass;
    private javax.swing.JButton Generateuser;
    private javax.swing.JPanel coverforget;
    private javax.swing.JTextField emailforget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField reset;
    private javax.swing.JTextField usernameshow;
    // End of variables declaration//GEN-END:variables

   public void method1(String T , String U ) 
    {
        this.mail = T;
        this.usernames = U;
    }

}
