package makanan;

import java.awt.Color;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame 
{
    String userlogin;
    String passlogin;
    String Emaillogin;
    
    public Register() 
    {
        initComponents();
          method(userlogin,passlogin,Emaillogin);
             method(userlogin,passlogin);
        jPanel4.setBackground(new Color(35,45,65,200));
        panellogo.setBackground(new Color(0,0,0,0));
        signpanel.setBackground(new Color(51,255,0,100));
        jPanel3.setBackground(new Color(255,51,51,100));
        forgotlog.setBackground(new Color(0,204,204,100));
      
            
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Userlog = new javax.swing.JTextField();
        Passlog = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        loginbottom = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        panellogo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signpanel = new javax.swing.JPanel();
        signpanel1 = new javax.swing.JPanel();
        signlabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        forgotlog = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        forgotlabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 40, 52));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(49, 54, 74));
        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN FORM");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, 50));

        Userlog.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        Userlog.setForeground(new java.awt.Color(153, 153, 153));
        Userlog.setText("Username");
        Userlog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Userlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserlogMouseClicked(evt);
            }
        });
        Userlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserlogActionPerformed(evt);
            }
        });
        jPanel4.add(Userlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 360, 60));

        Passlog.setForeground(new java.awt.Color(153, 153, 153));
        Passlog.setText("Input Password");
        Passlog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Passlog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasslogFocusGained(evt);
            }
        });
        Passlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasslogActionPerformed(evt);
            }
        });
        jPanel4.add(Passlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 360, 60));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Whatssapp: 0897667755443");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 180, 20));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("This is Unoffical Facultas Kopi Web");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 220, 20));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Facebook : FAKULTAS KOPI JAKARTA");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 260, 20));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Instagram: FAKULTAS KOPI");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, 20));

        loginbottom.setBackground(new java.awt.Color(255, 102, 0));
        loginbottom.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        loginbottom.setForeground(new java.awt.Color(255, 255, 255));
        loginbottom.setText("LETS EAT");
        loginbottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbottomActionPerformed(evt);
            }
        });
        jPanel4.add(loginbottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 130, 40));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 40, 30));

        jPanel12.setBackground(new java.awt.Color(51, 255, 0));
        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 40, 30));

        jPanel14.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 40, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 530, 610));

        panellogo.setPreferredSize(new java.awt.Dimension(250, 250));
        panellogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("jLabel3");
        panellogo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 440, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/1554131962224.png"))); // NOI18N
        panellogo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 290));

        jPanel2.add(panellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 260, 290));

        signpanel.setBackground(new java.awt.Color(51, 255, 0));
        signpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signpanelMouseClicked(evt);
            }
        });

        signpanel1.setBackground(new java.awt.Color(51, 255, 0));
        signpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signpanel1MouseClicked(evt);
            }
        });
        signpanel.add(signpanel1);

        signlabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        signlabel.setForeground(new java.awt.Color(255, 255, 255));
        signlabel.setText("SIGN UP");
        signlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signlabelMouseClicked(evt);
            }
        });
        signpanel.add(signlabel);

        jPanel2.add(signpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 120, 30));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.add(jPanel5);

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LOGIN");
        jPanel3.add(jLabel17);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 100, 30));

        forgotlog.setBackground(new java.awt.Color(0, 204, 204));
        forgotlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotlogMouseClicked(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(0, 204, 204));
        forgotlog.add(jPanel15);

        forgotlabel.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        forgotlabel.setForeground(new java.awt.Color(255, 255, 255));
        forgotlabel.setText("FORGET PASS?");
        forgotlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotlabelMouseClicked(evt);
            }
        });
        forgotlog.add(forgotlabel);

        jPanel2.add(forgotlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 140, 30));

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3);

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/black-coffee-1868462_1280.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x, y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void PasslogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasslogActionPerformed
        Passlog.setText("");
    }//GEN-LAST:event_PasslogActionPerformed

    private void PasslogFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasslogFocusGained
        Passlog.setText("");
    }//GEN-LAST:event_PasslogFocusGained

    private void UserlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserlogActionPerformed
        Userlog.setText("");
    }//GEN-LAST:event_UserlogActionPerformed

    private void UserlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserlogMouseClicked
        Userlog.setText("");
    }//GEN-LAST:event_UserlogMouseClicked

    private void loginbottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbottomActionPerformed
     String uname = Userlog.getText();
     String pass = Passlog.getText();
        
      if(uname.equals(userlogin) && pass.equals(passlogin))
      {
          
          Makan A = new Makan();
            this.dispose();
               A.setVisible(true);
      }
       else
     {
        JOptionPane.showMessageDialog(null,"Incorrect Username or Password","Warning",JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_loginbottomActionPerformed

    private void signpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signpanelMouseClicked
       Login A = new Login();
       A.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_signpanelMouseClicked

    private void signpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signpanel1MouseClicked
       Login A = new Login();
       A.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_signpanel1MouseClicked

    private void signlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signlabelMouseClicked
       Login A = new Login();
       A.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_signlabelMouseClicked

    private void forgotlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlabelMouseClicked
       forgetpass A = new forgetpass();
      A.method1(Emaillogin, userlogin);
       A.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_forgotlabelMouseClicked

    private void forgotlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotlogMouseClicked
      forgetpass A = new forgetpass();
      A.method1(Emaillogin, userlogin);
       A.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_forgotlogMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
    int exit = JOptionPane.showConfirmDialog(null,"Ingin Keluar?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
    if (exit == JOptionPane.YES_OPTION)
        {
          System.exit(0);
        }
    }//GEN-LAST:event_jPanel6MouseClicked
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int exit = JOptionPane.showConfirmDialog(null,"Ingin Keluar?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
            if (exit == JOptionPane.YES_OPTION)
                {
                  System.exit(0);
                }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }
 public void method(String A, String B, String C) 
    {
        this.userlogin =A;
        this.passlogin =B;
        this.Emaillogin =C;
    }

 public void method(String D, String E) 
    {
        this.userlogin =D;
        this.passlogin =E;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passlog;
    private javax.swing.JTextField Userlog;
    private javax.swing.JLabel forgotlabel;
    private javax.swing.JPanel forgotlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton loginbottom;
    private javax.swing.JPanel panellogo;
    private javax.swing.JLabel signlabel;
    private javax.swing.JPanel signpanel;
    private javax.swing.JPanel signpanel1;
    // End of variables declaration//GEN-END:variables

}
